In [3]:
import math

In [1]:
import numpy as np
a = np.matrix('-3.7 -13.9;0.2 -5.5;-4.1 -14;-1.5 -14.4;9.4 -2.9;-3 -8.8;-6.4 -8.7;-6.8 -12.8;2.5 -15.3;3.6 -7.9;-7.1 -12.2;0.5 -9.9;0.7 -15.2;-5.6 -15.3;-2.3 -6.6;1.7 -3.2;1.1 -11.3;-4.6 -12;3.8 -8.1;6.3 1.6;2.4 -7.2;-2.5 -7.7;1.3 -9;0.9 -9.4;8.9 0.2;1.8 -7.8;-0.3 -10.1;10 -0.3;5.4 -4;0.2 -3.8;-0.6 -3.6;7.1 -4.4;-4.5 -8.2;6.5 -8.2;-6.5 -11.9;0.4 -13.2;4.9 -6.6;-4.4 -9.6;-2.6 -13.4;-8.8 -12.1;-3.7 -9.2;-3.8 -9.9;-1.9 -9.1;0.8 -5.1;-3.9 -9;2.5 -13.1;4 -6.7;-4.1 -7.4;-2.8 -6.7;-0.5 -2.9;7.7 -2.6;-2.4 -6.9;5.3 -6.5;4.2 -2.8;-1.9 -12.6;-1.3 -13.1;1.3 -5.9;-3.8 -11.3;-7.7 -12.5;-2.4 -11.6;2.8 -11.6;-0.3 -11.9;3.6 -12.2;0 -10.6;-10 -13.7;-5 -15;-1.5 -9.1;-3.9 -13.4;-5.4 -15.7;3.1 -11;-0.8 -11.8;-11.7 -15.4;-9 -15.4;-5 -14.8;-1 -5.1;0 -2.3;0 -2.9;1.2 -4.8;-0.1 -7.6;0.1 -10.3;5.7 -2.4;-1.9 -6.4;0.9 -6.2;-1.6 -5.9;3.9 -7.1;5.2 0.3;3.4 -1.9;4.4 -4.9;2 -5.5;1.1 -5.7;4.4 -1.3;-0.5 -6.7;0.6 -6.8;7.8 -2.2;6.6 -6.7;-1.3 -7.9;-0.3 -9.6;0.5 -9.6;-2.4 -12.2;-1.2 -9.3;8.1 -2.3;3.3 -3.3;3.2 -4.1;11.7 -1.7;9.4 -3.6;-3.4 -7.1;4.1 -7.3;6.2 -2.9;-1.2 -4.2;1.1 -4.4;3.1 -4.5;3 -3.6;3.5 -0.8;3.6 -1;5.3 -0.8;6.2 0.3;3.8 -0.3;4.3 -0.1;7.3 -0.6;1.4 0.2;2.8 0.1;8.1 0.2;9 2.2;14.8 3.1;18.3 2.2;12 -0.9;8.5 -2;1.9 -2.3;6.2 0.3;8 0.4;8.1 -2.3;11.5 -1.5;8.1 -0.6;9.2 -0.2;17.9 2.5;14.5 -0.9;7.1 -1.2;4.5 1.9;17.4 2.6;16.3 8.4;14.5 4.3;17.8 3;13 3.8;14.5 2.8;19.9 6.2;24 6.4;15.2 7.2;16.4 7;8.4 1;18.8 1.8;19 2.8;6.5 -1.6;10.8 -1.8;11.8 1.6;8.3 -0.2;14.2 -0.8;15 3.4;15.6 2.8;11.7 2.2;19 4.3;20.1 5.2;21.5 6.8;19.9 11.1;13.9 4.3;9.9 4.3;10.4 3.2;16.2 5.3;13.1 4.6;23 4.4;20 7.4;19.4 8.1;20.6 7.3;17.1 7.1;10.4 3.5;9.9 4;7.6 5.3;9.4 5.2;9.4 3.6;22.3 3.5;17.7 7.6;21.3 8.2;19.2 8.8;15.4 7.9;25.3 8.9;19.5 11.2;15.5 8.2;8.5 5.7;14.4 5.9;19.1 9.9;23.1 13.8;22.2 7.4;10.9 6.5;13.6 6.3;16.5 8.5;20 9.6;16 11.1;23.8 13.3;18.3 8.7;14.8 7.9;11.2 7.7;11.7 7.5;11.3 8.1;11.7 8.2;18 9.6;9.8 6.3;9.7 5.8;10.6 6.5;18.2 8.4;19.5 7.7;16.4 9.5;12.7 9.1;14 9;14.5 9.4;27.1 13.9;25.5 13.1;22.2 12.1;26.4 12.1;23 14.4;24.5 10.8;18.9 10.5;12.2 9.8;26 10.6;24.4 11;21 10.2;25.4 20.4;22.5 16;25.7 15.3;24.9 16;21.8 12.8;27.3 12.9;17.4 12.1;18 12.3;25.2 14.8;26.9 17.5;23.4 18.3;21.4 13.7;15.2 10.4;17.7 10.1;22.2 10;22.1 11.4;23.7 13.1;23.1 12.4;22.5 15.5;21.1 10.1;11 6.7;22.4 8.6;15.2 6.6;16.8 6.3;16.7 5.5;23.3 9.9;11.8 2.2;14.8 1.7;22 12;22.1 12.1;15.5 11.7;25.5 11.4;17.2 10.7;18.7 12.3;14.2 6.8;15.2 6.6;15.3 4.8;22.8 5.5;22.5 13.1;19 6.2;14.9 4.6;20.3 4.2;20.1 7.3;12.6 3.5;9.7 1.3;12.1 1;18.6 12.1;23 12.3;23.6 14.4;22.8 15.8;16.9 5.8;6.6 4.5;8 1.6;14.7 2.4;17.3 6.6;9.9 6.6;15.9 5.1;11.2 3.7;14.9 3.1;9.2 2.8;13.4 5.2;16 7.2;23.7 11.8;18.5 8.6;11 3.2;12.9 2;11.4 0.8;6.7 2.7;10.8 2.5;10.6 2.6;7.6 2.1;13.4 3.5;4.1 -0.9;10.1 -0.6;14.8 0.6;2.8 -0.9;3.9 -0.5;13.7 -1.6;16.8 5;6.1 2.7;7.4 1.5;11.9 2.1;2.6 -1.6;1.4 -1.7;1.5 -2.2;6.9 -1.1;13 4;6 0.5;2.8 0;6.5 -1.4;2.7 -3.8;1.4 -2;3.9 0.3;4.8 3.7;5.1 0.6;1.6 0.3;2.7 0.2;1.4 -1;0.7 -0.9;3.3 -0.7;3.1 -1.8;7.2 -2;8 2;9.8 0.9;1.8 -2.6;2.3 -4.1;10 2.2;9.8 -0.4;0.6 -5.2;-5.1 -9;-0.5 -8.7;6.4 -0.9;11.5 -2.8;-2.5 -5.6;-0.5 -6.2;1.6 -6.6;3.5 1.4;2.2 -2.1;-0.7 -2.3;1.4 -1.1;4.4 1.3;6 3.5;4.5 -1.7;-0.5 -2.4;-0.5 -1.8;-0.6 -2.1;-1.8 -7.8;2.2 -7;11.7 0.1;0.4 -2.8;-0.3 -2.8;-1.1 -11.8;-3.9 -12.4;1 -7.1;6.8 -0.2;1 -2.8;-1.9 -6.4;-6.1 -11.5;-7.5 -12.1;-6.3 -11.2;-1.9 -10.3')


In [2]:
a


matrix([[ -3.7, -13.9],
        [  0.2,  -5.5],
        [ -4.1, -14. ],
        [ -1.5, -14.4],
        [  9.4,  -2.9],
        [ -3. ,  -8.8],
        [ -6.4,  -8.7],
        [ -6.8, -12.8],
        [  2.5, -15.3],
        [  3.6,  -7.9],
        [ -7.1, -12.2],
        [  0.5,  -9.9],
        [  0.7, -15.2],
        [ -5.6, -15.3],
        [ -2.3,  -6.6],
        [  1.7,  -3.2],
        [  1.1, -11.3],
        [ -4.6, -12. ],
        [  3.8,  -8.1],
        [  6.3,   1.6],
        [  2.4,  -7.2],
        [ -2.5,  -7.7],
        [  1.3,  -9. ],
        [  0.9,  -9.4],
        [  8.9,   0.2],
        [  1.8,  -7.8],
        [ -0.3, -10.1],
        [ 10. ,  -0.3],
        [  5.4,  -4. ],
        [  0.2,  -3.8],
        [ -0.6,  -3.6],
        [  7.1,  -4.4],
        [ -4.5,  -8.2],
        [  6.5,  -8.2],
        [ -6.5, -11.9],
        [  0.4, -13.2],
        [  4.9,  -6.6],
        [ -4.4,  -9.6],
        [ -2.6, -13.4],
        [ -8.8, -12.1],
        [ -3.7,  -9.2],
        [ -3.8, 

In [5]:
a.sum(axis=1)

matrix([[-17.6],
        [ -5.3],
        [-18.1],
        [-15.9],
        [  6.5],
        [-11.8],
        [-15.1],
        [-19.6],
        [-12.8],
        [ -4.3],
        [-19.3],
        [ -9.4],
        [-14.5],
        [-20.9],
        [ -8.9],
        [ -1.5],
        [-10.2],
        [-16.6],
        [ -4.3],
        [  7.9],
        [ -4.8],
        [-10.2],
        [ -7.7],
        [ -8.5],
        [  9.1],
        [ -6. ],
        [-10.4],
        [  9.7],
        [  1.4],
        [ -3.6],
        [ -4.2],
        [  2.7],
        [-12.7],
        [ -1.7],
        [-18.4],
        [-12.8],
        [ -1.7],
        [-14. ],
        [-16. ],
        [-20.9],
        [-12.9],
        [-13.7],
        [-11. ],
        [ -4.3],
        [-12.9],
        [-10.6],
        [ -2.7],
        [-11.5],
        [ -9.5],
        [ -3.4],
        [  5.1],
        [ -9.3],
        [ -1.2],
        [  1.4],
        [-14.5],
        [-14.4],
        [ -4.6],
        [-15.1],
        [-20.2

In [16]:
gdd=(a.sum(axis=1)/2)-10

In [17]:
gdd


matrix([[-18.8 ],
        [-12.65],
        [-19.05],
        [-17.95],
        [ -6.75],
        [-15.9 ],
        [-17.55],
        [-19.8 ],
        [-16.4 ],
        [-12.15],
        [-19.65],
        [-14.7 ],
        [-17.25],
        [-20.45],
        [-14.45],
        [-10.75],
        [-15.1 ],
        [-18.3 ],
        [-12.15],
        [ -6.05],
        [-12.4 ],
        [-15.1 ],
        [-13.85],
        [-14.25],
        [ -5.45],
        [-13.  ],
        [-15.2 ],
        [ -5.15],
        [ -9.3 ],
        [-11.8 ],
        [-12.1 ],
        [ -8.65],
        [-16.35],
        [-10.85],
        [-19.2 ],
        [-16.4 ],
        [-10.85],
        [-17.  ],
        [-18.  ],
        [-20.45],
        [-16.45],
        [-16.85],
        [-15.5 ],
        [-12.15],
        [-16.45],
        [-15.3 ],
        [-11.35],
        [-15.75],
        [-14.75],
        [-11.7 ],
        [ -7.45],
        [-14.65],
        [-10.6 ],
        [ -9.3 ],
        [-17.25],
        [-

In [18]:
gddy=gdd.sum(axis=0)

In [19]:
gddy


matrix([[-2002.15]])

In [ ]:
def gdd(inputData)
